"""initial

Revision ID: d40f89382b20
Revises: e14038a4899e
Create Date: 2026-04-09 12:10:50.099556
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'd40f89382b20'
down_revision: Union[str, None] = 'e14038a4899e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
