"""initial

Revision ID: d7fafc9200ed
Revises: 
Create Date: 2026-04-08 09:53:10.363100
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'd7fafc9200ed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target', sa.String(length=120), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action_ts', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index('ix_audit_username_ts', 'audit_logs', ['username', 'created_at'], unique=False)
    op.create_table('setores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_setores_id'), 'setores', ['id'], unique=False)
    op.create_table('equipamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('patrimonio', sa.String(length=60), nullable=True),
    sa.Column('fabricante', sa.String(length=120), nullable=True),
    sa.Column('modelo', sa.String(length=120), nullable=True),
    sa.Column('temp_min', sa.Float(), nullable=True),
    sa.Column('temp_max', sa.Float(), nullable=True),
    sa.Column('umid_min', sa.Float(), nullable=True),
    sa.Column('umid_max', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('motivo_inativacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['setor_id'], ['setores.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_equip_setor_active', 'equipamentos', ['setor_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_equipamentos_id'), 'equipamentos', ['id'], unique=False)
    op.create_index(op.f('ix_equipamentos_setor_id'), 'equipamentos', ['setor_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nome_completo', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['setor_id'], ['setores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('sensores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipamento_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=True),
    sa.Column('protocolo', sa.String(length=20), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('ultimo_sinal', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamentos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensores_equipamento_id'), 'sensores', ['equipamento_id'], unique=False)
    op.create_index(op.f('ix_sensores_id'), 'sensores', ['id'], unique=False)
    op.create_table('alertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('equipamento_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('valor_registrado', sa.Float(), nullable=True),
    sa.Column('valor_limite', sa.Float(), nullable=True),
    sa.Column('inicio_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fim_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reconhecido_por', sa.String(length=80), nullable=True),
    sa.Column('reconhecido_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nivel_escalonamento', sa.Integer(), nullable=False),
    sa.Column('proxima_escalonamento_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamentos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerta_sensor_tipo_ativo', 'alertas', ['sensor_id', 'tipo', 'fim_at'], unique=False)
    op.create_index(op.f('ix_alertas_equipamento_id'), 'alertas', ['equipamento_id'], unique=False)
    op.create_index(op.f('ix_alertas_id'), 'alertas', ['id'], unique=False)
    op.create_index(op.f('ix_alertas_sensor_id'), 'alertas', ['sensor_id'], unique=False)
    op.create_table('leituras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('temperatura', sa.Float(), nullable=True),
    sa.Column('umidade', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leitura_sensor_ts', 'leituras', ['sensor_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_leituras_id'), 'leituras', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leituras_id'), table_name='leituras')
    op.drop_index('ix_leitura_sensor_ts', table_name='leituras')
    op.drop_table('leituras')
    op.drop_index(op.f('ix_alertas_sensor_id'), table_name='alertas')
    op.drop_index(op.f('ix_alertas_id'), table_name='alertas')
    op.drop_index(op.f('ix_alertas_equipamento_id'), table_name='alertas')
    op.drop_index('ix_alerta_sensor_tipo_ativo', table_name='alertas')
    op.drop_table('alertas')
    op.drop_index(op.f('ix_sensores_id'), table_name='sensores')
    op.drop_index(op.f('ix_sensores_equipamento_id'), table_name='sensores')
    op.drop_table('sensores')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_equipamentos_setor_id'), table_name='equipamentos')
    op.drop_index(op.f('ix_equipamentos_id'), table_name='equipamentos')
    op.drop_index('ix_equip_setor_active', table_name='equipamentos')
    op.drop_table('equipamentos')
    op.drop_index(op.f('ix_setores_id'), table_name='setores')
    op.drop_table('setores')
    op.drop_index('ix_audit_username_ts', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index('ix_audit_action_ts', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
