"""initial

Revision ID: e14038a4899e
Revises: e1e063c3a870
Create Date: 2026-04-08 10:07:46.573942
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e14038a4899e'
down_revision: Union[str, None] = 'e1e063c3a870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
