"""initial

Revision ID: e1e063c3a870
Revises: d7fafc9200ed
Create Date: 2026-04-08 09:58:30.225713
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e1e063c3a870'
down_revision: Union[str, None] = 'd7fafc9200ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
